// <auto-generated />
using Fortion.API.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fortion.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210916165106_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("Fortion.API.Domain.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("WarehouseTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseTypeId");

                    b.ToTable("warehouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Beautiful wharehouse",
                            ImageUrl = "https://www.prologis.com/sites/corporate/files/images/2019/09/large-ontario_dc9_3_11.jpg",
                            WarehouseTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Another beautiful wharehouse",
                            ImageUrl = "https://www.americanwarehouses.com/hubfs/AmericanWarehouses_Blog_TheBestApproachToLeasingWarehouseSpace.jpg",
                            WarehouseTypeId = 4
                        },
                        new
                        {
                            Id = 3,
                            Description = "Beautiful wharehouse",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFUF7sF6E0m-8enGRPS0RHn-FbCraPQLkeeg&usqp=CAU",
                            WarehouseTypeId = 3
                        });
                });

            modelBuilder.Entity("Fortion.API.Domain.Models.WarehouseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Length")
                        .HasColumnType("double");

                    b.Property<double>("Width")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("WarehouseTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Length = 4.0,
                            Width = 4.0
                        },
                        new
                        {
                            Id = 2,
                            Length = 1.0,
                            Width = 1.0
                        },
                        new
                        {
                            Id = 3,
                            Length = 2.0,
                            Width = 2.0
                        },
                        new
                        {
                            Id = 4,
                            Length = 3.0,
                            Width = 3.0
                        },
                        new
                        {
                            Id = 5,
                            Length = 5.0,
                            Width = 5.0
                        });
                });

            modelBuilder.Entity("Fortion.API.Domain.Models.Warehouse", b =>
                {
                    b.HasOne("Fortion.API.Domain.Models.WarehouseType", "WarehouseType")
                        .WithMany("Warehouses")
                        .HasForeignKey("WarehouseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WarehouseType");
                });

            modelBuilder.Entity("Fortion.API.Domain.Models.WarehouseType", b =>
                {
                    b.Navigation("Warehouses");
                });
#pragma warning restore 612, 618
        }
    }
}
